[build-system]
requires = ["setuptools", "setuptools-scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "vqvae"
description = "PyTorch implementation of VQ-VAE"
requires-python = ">=3.7,<3.10"
keywords = ["pytorch", "vq-vae", "vqvae", "vector-quantized-vae", "vector-quantized-autoencoder"]
license = {text = "MIT"}
readme = "readme_pip.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "torch>=1.8",
    "pytorch-lightning >= 1.8",
    "torchvision",
    "tensorguard==1.0.0"
]

version = "1.0.2"

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["vqvae"]
