# dataset metadata
width: 32
height: 32
channels: 3
num_classes: 10
files_location: ~/.cache/torchvision_dataset
instance:
  _target_: torchvision.datasets.CIFAR10
  root: ${dataset.files_location}
  train: true
  download: true
  transform:
    _target_: torchvision.transforms.ToTensor
